### ISSUE TITLE
Please change bubble sum from 40 to 50, 60 and so on.

### ISSUE THREAD

**Issue by radharai** [prepitt/bubble#23]
From level 4 onwards till level 31, I got bubble sum as 40. Please change bubble sum after every 5 levels

for instance:

Level1 - 5  - Bubble sum 30
Level 6- 10- Bubble sum 40
Level 11- 15, bubble sum 50 and so on.

Since Code is configurable, pop in bubble of 30 cents, 25 cents to make bubble sum of 60 etc.

**Comment by Navjotkaur12** [comment]
we will discuss this on the call.

**Comment by Navjotkaur12** [comment]
Hi,

Initially game block sum was stated to be 30 & 40 cents .I coded it that
way .The code is configurable but it would take 8 hours extra effort to do
this ( I need to make changes to code, add more conditions etc ).It would
be chargeable as I have coded the 50 levels already ( 1-2 level with sum 30
, 3-30 level with 40 sum & 30-50  with 50 sum ) there was nowhere defined
that bubble would be having 30 cents, 25 cents bubble too and the sum would
lead to 60 & so on  .I hope you will understand.

I have coded the tips to appear randomly ,For appearance of tips on
particular power bubble & etc it would also take another 3 hours effort .

Suggestion : we could also do this for update version of this game .

Regards

**Comment by radharai** [comment]
If you look at the requirements document, slide #2 (Starting Standards) - there are two things mentioned:
1. Different block numbers: 25, 30, 35, 40
2. Max bubble size: 25

Abhijit would like to understand how its coded that it gets to be difficult to add additional bubble sizes / block numbers.

**Comment by Navjotkaur12** [comment]
Hi Everyone,

I just came to know about the issue and i must say we never received any
such presentation which says that we are going to use blocks of numbers 25,
30, 35, 40
It is only 30 or 40 always and things are coded that way.

I am attaching the presentation file we received.

These changes are going to be extra efforts than what was decided initially
because it was not considered in the initial estimation which is going to
be around 7-8 Hours of a day.

We are open to changes but we need to reconsider the efforts in case there
is something which is not considered in past i hope you understand this
thing.

Team will share with you guys as well in case you want to check the logic
prepared for this part or i guess you must be having the code already.

Please approve the hours of the efforts and lets get things moving as we
are almost on the finish line.

Waiting to hear back from you guys on this.

Best Regards
Amit Singh

**Comment by radharai** [comment]
No worries. Let's discuss on the call today at 8am.
Thanks

**Comment by Navjotkaur12** [comment]
Sure ,will be waiting for same .
